spring.application.name=complaint-system-backend

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/complaintapp
spring.data.mongodb.database=complaintapp

# Server Port
server.port=8080
